import './globals.css';
import { notFound } from 'next/navigation';
import { NextIntlClientProvider } from 'next-intl';
import Header from '@/components/Header';
import PageTransition from '@/components/ui/PageTransition';
import { getFaviconIfExists } from '@/lib/favicon';
import { JetBrains_Mono } from 'next/font/google';

const locales = ['en', 'fr'];
const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-jetbrainsMono',
});

export async function generateMetadata() {
  const icon = getFaviconIfExists();

  return {
    title: 'Imane_Portfolio',
    description: 'Generated by Imane',
    icons: icon ? { icon } : undefined,
  };
}

export default async function LocaleLayout({ children, params }) {
  const { locale } = params;
  if (!locales.includes(locale)) {
    notFound();
  }
  const messages = (await import(`../../../messages/${locale}.json`)).default;
  return (
    <html lang={locale}>
      <body className={`${jetbrainsMono.variable}`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Header />
          <PageTransition>{children}</PageTransition>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
